version: '3.9'
services:
  jupyternotebook:
    image: ghcr.io/yanorei32/uthree-ml-image:0.2.0
    hostname: jupyternotebook
    container_name: uthreeml__jupyternotebook
    restart: unless-stopped
    init: true

    environment:
      SHELL: "/bin/zsh"

    volumes:
      - type: volume
        source: workdir
        target: /root

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 16g
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  cloudflared:
    image: cloudflare/cloudflared:2022.8.0
    hostname: cloudflared
    container_name: uthreeml__cloudflared

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_URL: http://jupyternotebook:8080
      TUNNEL_HOSTNAME: uthreeml-testing.yr32.net
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel
    user: root

    restart: unless-stopped

    volumes:
      - type: bind
        source: /etc/cloudflared/cert.pem
        target: /etc/cloudflared/cert.pem
        read_only: true

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 128m

  nginxcompat:
    image: nginx:1.23.1
    hostname: nginxcompat
    container_name: uthreeml__nginxcompat
    restart: unless-stopped

    volumes:
      - type: bind
        source: ./nginx.compat.conf
        target: /etc/nginx/nginx.conf
        read_only: true

    networks:
      - nginxcompat_cloudflaredcompat

    deploy:
      resources:
        limits:
          memory: 128m

  cloudflaredcompat:
    image: cloudflare/cloudflared:2022.8.0
    hostname: cloudflaredcompat
    container_name: uthreeml__cloudflaredcompat
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_URL: http://nginxcompat:80
      TUNNEL_HOSTNAME: jupyter.yr32.net
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel
    user: root

    volumes:
      - type: bind
        source: /etc/cloudflared/cert.pem
        target: /etc/cloudflared/cert.pem
        read_only: true

    networks:
      nginxcompat_cloudflaredcompat:
      cloudflaredcompat_internet:
      prometheus__cloudflared:
        aliases:
          - uthreeml__cloudflaredcompat

    deploy:
      resources:
        limits:
          memory: 128m

volumes:
  workdir:
    name: uthreeml__workdir

networks:
  prometheus__cloudflared:
    name: prometheus__cloudflared
    external: true

  default:
    name: uthreeml__default

  nginxcompat_cloudflaredcompat:
    name: uthreeml__nginxcompat_cloudflaredcompat
    internal: true

  cloudflaredcompat_internet:
    name: uthreeml__cloudflaredcompat_internet
