version: '3.9'
services:
  squid:
    image: ubuntu/squid:5.2-22.04_beta@sha256:315a92c0fe6041b5479dc58f3bb6c2316aa93f48d16e49c58e002d821f2d30ad
    hostname: squid
    container_name: uthreeml__squid
    restart: unless-stopped

    volumes:
      - type: bind
        source: ./squid.conf
        target: /etc/squid/squid.conf
        read_only: true

    networks:
      - default
      - outband

    deploy:
      resources:
        limits:
          memory: 256m

  jupyternotebook:
    image: ghcr.io/yanorei32/uthree-ml-image:0.5.6
    hostname: jupyternotebook
    container_name: uthreeml__jupyternotebook
    restart: unless-stopped
    init: true

    environment:
      SHELL: "/bin/zsh"
      http_proxy: http://squid:3128
      https_proxy: http://squid:3128

    volumes:
      - type: volume
        source: workdir
        target: /root

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 16g
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  cloudflared:
    image: cloudflare/cloudflared:2022.10.3-amd64@sha256:d3840dadf665098fa7307aeec68f1ce8802437559cb06cf3863afcf963a02f6d
    hostname: cloudflared
    container_name: uthreeml__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    networks:
      default:
      outband:
      prometheus__cloudflared:
        aliases:
          - uthreeml__cloudflared

    deploy:
      resources:
        limits:
          memory: 128m

volumes:
  workdir:
    name: uthreeml__workdir

networks:
  prometheus__cloudflared:
    name: prometheus__cloudflared
    external: true

  default:
    name: uthreeml__default
    internal: true

  outband:
    name: uthreeml__outband
