version: '3.9'
services:
  squid:
    image: ubuntu/squid:5.2-22.04_beta@sha256:64d96dc919de679121bc26df15bd5fea7e5e796a8de8f7977b8a21212ddbff92
    hostname: squid
    container_name: uthreeml__squid
    restart: unless-stopped

    volumes:
      - type: bind
        source: ./squid.conf
        target: /etc/squid/squid.conf
        read_only: true

    networks:
      - default
      - outband

    deploy:
      resources:
        limits:
          memory: 256m

  jupyternotebook:
    build: https://github.com/yanorei32/uthree-ml-image.git#v0.7.3
    hostname: jupyternotebook
    container_name: uthreeml__jupyternotebook
    restart: unless-stopped
    init: true

    environment:
      SHELL: "/bin/zsh"
      http_proxy: http://squid:3128
      https_proxy: http://squid:3128

    volumes:
      - type: volume
        source: workdir
        target: /root

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 16g
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  cloudflared:
    image: cloudflare/cloudflared:2023.8.2-amd64@sha256:680085f76a59c53b7827a170d43dbdc9ef87235af6c39c9d4d028fde38359233
    hostname: cloudflared
    container_name: uthreeml__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    networks:
      default:
      outband:
      prometheus__cloudflared:
        aliases:
          - uthreeml__cloudflared

    deploy:
      resources:
        limits:
          memory: 128m

volumes:
  workdir:
    name: uthreeml__workdir

networks:
  prometheus__cloudflared:
    name: prometheus__cloudflared
    external: true

  default:
    name: uthreeml__default
    internal: true

  outband:
    name: uthreeml__outband
