version: '3.9'
services:
  squid:
    image: ubuntu/squid:5.2-22.04_beta@sha256:d4897d684bb150d5325af0e39f35087c0714509f914760e5db8a3679ef26222b
    hostname: squid
    container_name: uthreeml__squid
    restart: unless-stopped

    volumes:
      - type: bind
        source: ./squid.conf
        target: /etc/squid/squid.conf
        read_only: true

    networks:
      - default
      - outband

    deploy:
      resources:
        limits:
          memory: 256m

  jupyternotebook:
    image: ghcr.io/yanorei32/uthree-ml-image:0.5.6
    hostname: jupyternotebook
    container_name: uthreeml__jupyternotebook
    restart: unless-stopped
    init: true

    environment:
      SHELL: "/bin/zsh"
      http_proxy: http://squid:3128
      https_proxy: http://squid:3128

    volumes:
      - type: volume
        source: workdir
        target: /root

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 16g
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  cloudflared:
    image: cloudflare/cloudflared:2022.12.0-amd64@sha256:838aa0ffae2c8aff2313f563e711166648344e6be22d741c82c2d5084779d56d
    hostname: cloudflared
    container_name: uthreeml__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    networks:
      default:
      outband:
      prometheus__cloudflared:
        aliases:
          - uthreeml__cloudflared

    deploy:
      resources:
        limits:
          memory: 128m

volumes:
  workdir:
    name: uthreeml__workdir

networks:
  prometheus__cloudflared:
    name: prometheus__cloudflared
    external: true

  default:
    name: uthreeml__default
    internal: true

  outband:
    name: uthreeml__outband
