name: lint actions

on:
  pull_request:
    paths:
      - '.github/workflows/**'

jobs:
  lint-actionlint:
    runs-on: ubuntu-20.04

    steps:
       - uses: actions/checkout@v3.0.2

       - uses: reviewdog/action-actionlint@v1.32.0
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           reporter: github-pr-check
