name: validate squid

on:
  pull_request:
    paths:
      - 'squid.conf'
      - '.github/workflows/validate-squid.yml'

jobs:
  validate-squid:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3.0.2

      - uses: actions/setup-node@v3.4.1

      - name: install
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq nginx

      - name: validate
        shell: bash
        run: |
          sudo useradd -M nginx
          shopt -s globstar
          set -eux

          for f in **/nginx*.conf; do
              if ! nginx -t -c "$f"; then
                  exit 1
              fi
          done

          exit 0
