name: validate squid

on:
  pull_request:
    paths:
      - 'squid.conf'
      - '.github/workflows/validate-squid.yml'

jobs:
  validate-squid:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - uses: actions/setup-node@v3.8.1

      - name: install
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq squid

      - name: validate
        shell: bash
        run: |
          shopt -s globstar
          set -eux

          for f in **/squid.conf; do
              if ! squid -f "$f" -k parse; then
                  exit 1
              fi
          done

          exit 0
